version: "3.9"

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: minha_senha
  postgres:
    image: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: minha_senha
     POSTGRES_DB: postgres
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
